name: UI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Build UI
        run: pnpm build
